// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type networkerFlowKey struct {
	_          structs.HostLayout
	Local      [16]uint8
	Remote     [16]uint8
	LocalPort  uint16
	RemotePort uint16
	Family     uint8
	Protocol   uint8
	Pad        uint16
}

type networkerFlowValue struct {
	_        structs.HostLayout
	FirstNs  uint64
	LastNs   uint64
	Sent     uint64
	Received uint64
	Cookie   uint64
	Pid      uint32
	_        [4]byte
	Flags    uint64
	Comm     [16]int8
}

type networkerOwner struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

// loadNetworker returns the embedded CollectionSpec for networker.
func loadNetworker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load networker: %w", err)
	}

	return spec, err
}

// loadNetworkerObjects loads networker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*networkerObjects
//	*networkerPrograms
//	*networkerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetworkerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetworker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// networkerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkerSpecs struct {
	networkerProgramSpecs
	networkerMapSpecs
	networkerVariableSpecs
}

// networkerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkerProgramSpecs struct {
	Connect4 *ebpf.ProgramSpec `ebpf:"connect4"`
	Connect6 *ebpf.ProgramSpec `ebpf:"connect6"`
	Egress   *ebpf.ProgramSpec `ebpf:"egress"`
	Ingress  *ebpf.ProgramSpec `ebpf:"ingress"`
	Sendmsg4 *ebpf.ProgramSpec `ebpf:"sendmsg4"`
	Sendmsg6 *ebpf.ProgramSpec `ebpf:"sendmsg6"`
}

// networkerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkerMapSpecs struct {
	DnsQueries *ebpf.MapSpec `ebpf:"dns_queries"`
	Flows      *ebpf.MapSpec `ebpf:"flows"`
	Owners     *ebpf.MapSpec `ebpf:"owners"`
}

// networkerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkerVariableSpecs struct {
}

// networkerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetworkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkerObjects struct {
	networkerPrograms
	networkerMaps
	networkerVariables
}

func (o *networkerObjects) Close() error {
	return _NetworkerClose(
		&o.networkerPrograms,
		&o.networkerMaps,
	)
}

// networkerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetworkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkerMaps struct {
	DnsQueries *ebpf.Map `ebpf:"dns_queries"`
	Flows      *ebpf.Map `ebpf:"flows"`
	Owners     *ebpf.Map `ebpf:"owners"`
}

func (m *networkerMaps) Close() error {
	return _NetworkerClose(
		m.DnsQueries,
		m.Flows,
		m.Owners,
	)
}

// networkerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetworkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkerVariables struct {
}

// networkerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetworkerObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkerPrograms struct {
	Connect4 *ebpf.Program `ebpf:"connect4"`
	Connect6 *ebpf.Program `ebpf:"connect6"`
	Egress   *ebpf.Program `ebpf:"egress"`
	Ingress  *ebpf.Program `ebpf:"ingress"`
	Sendmsg4 *ebpf.Program `ebpf:"sendmsg4"`
	Sendmsg6 *ebpf.Program `ebpf:"sendmsg6"`
}

func (p *networkerPrograms) Close() error {
	return _NetworkerClose(
		p.Connect4,
		p.Connect6,
		p.Egress,
		p.Ingress,
		p.Sendmsg4,
		p.Sendmsg6,
	)
}

func _NetworkerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed networker_bpfeb.o
var _NetworkerBytes []byte
